# Generated by Django 4.2.3 on 2023-08-01 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_rename_description_menu_menu_item_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
    ]
